version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: db_base
      POSTGRES_USER: user_access
      POSTGRES_PASSWORD: password_access
    ports:
      - "5432:5432"
    volumes:
      - ./db_base.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: data-dictionary-app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      
volumes:
  postgres_data:
